# Generated by Django 5.1 on 2024-08-24 11:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(verbose_name=64)),
                ('last_name', models.CharField(verbose_name=64)),
                ('phone_number', models.CharField(verbose_name=13)),
                ('email', models.CharField(verbose_name=64)),
                ('password', models.CharField(verbose_name=64)),
                ('is_admin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 8, 24, 11, 55, 40, 342386), editable=False)),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2024, 8, 24, 11, 55, 40, 342415))),
            ],
        ),
    ]
